### ISSUE TITLE
Beta issues

### ISSUE THREAD

**Issue by talmog** [wardbell/ng2BabyUnitTest#7]
Hi,
Thank you again for the examples, they are very useful.
I am trying to use test-helpers with Beta, and it seems RootTestComponent doesn't have debugElement method anymore.
Are you intending to upgrade this repo to Beta? 
Thanks you!

**Comment by wardbell** [comment]
Oh yes indeed!  

To be honest, this repo is a way-station on the way to perfecting Angular's own docs. It will likely be folded into the document samples there.

**Comment by talmog** [comment]
thank you!
